apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.secret.name }}"
type: Opaque
data:
  DB_SERVER: {{ .Values.secret.data.DB_SERVER | b64enc | quote }}
  DB_USERNAME: {{ .Values.secret.data.DB_USERNAME | b64enc | quote }}
  DB_PASSWORD: {{ .Values.secret.data.DB_PASSWORD | b64enc | quote }}
  DB_DATABASE: {{ .Values.secret.data.DB_DATABASE | b64enc | quote }}